/****************************************************************** RUNTIME.H
 *                                                                          *
 *                  Escriba Word Processor for OS/2-PM                      *
 *                                                                          *
 ****************************************************************************/

#ifndef RUNTIME_H
#define RUNTIME_H

#define REVISION     "RunTime 0.96c"
#define REVISION_NO  (96)

#define PROGRAM_NAME "RUNTIME"
#define LOGFILE      PROGRAM_NAME ".LOG"

#endif 
