/* PCX User API functions */

#ifndef PCX_H
#define PCX_H

#define REVISION     "PCX 0.97"
#define REVISION_NO  (97)

#define ID_HELPTABLE            1

#define IDD_PRODUCTINFO         1

#define IDS_TITLE               1
#define IDS_TITLE1              2
#define IDS_HELPTITLE           3
#define IDS_ERROR_CREATEHELP    4

#define IDS_ERROR_OPEN_FOR_VERIFY               0x1000
#define IDS_ERROR_FILE_TOO_SMALL                0x1001
#define IDS_ERROR_INVALID_FILE_ID               0x1002
#define IDS_ERROR_PLANAR                        0x1003
#define IDS_ERROR_INVALID_PALETTE               0x1004
#define IDS_ERROR_INVALID_PALETTE_SIZE          0x1005
#define IDS_ERROR_MEMORY1                       0x1006
#define IDS_ERROR_MEMORY2                       0x1007
#define IDS_ERROR_DC_OPEN                       0x1008
#define IDS_ERROR_PS_CREATE                     0x1009
#define IDS_ERROR_CREATE_BITMAP                 0x100A
#define IDS_ERROR_OPEN_FOR_LOAD                 0x100B
#define IDS_ERROR_MEMORY3                       0x100C

#endif /* PCX_H */
