/******************************************************************** FRAME.H
 *                                                                          *
 *                      Main Window Frame (Subclassed)                      *
 *                                                                          *
 ****************************************************************************/

#ifndef FRAME_H
#define FRAME_H

#include "System.h"

#define FRAME_CLASS_NAME "Frame"

extern WINDOWPROC FrameMessageProcessor ;

#endif
