Escriba Word Processor for OS/2 Presentation Manager
====================================================

  This program provides a What You See Is What You Get (WYSIWYG) word processor for the OS/2 Presentation Manager interface.  It does not attempt to go head-to-head with the large professional word processors available for OS/2 PM or Windows, but rather tries to provide a more modest set of functions.  Normal text formatting is provided for, plus the program has the ability to handle embedded graphics.  All installed ATM fonts are supported, in all the native formats and in a wide range of sizes.  Printer support is strictly through the OS/2 PM interface, providing output on any printer supported by that interface, including FAX and plotter devices.
