/* GIF User API functions */

#ifndef GIF_H
#define GIF_H

#define REVISION     "GIF 0.97"
#define REVISION_NO  (97)

#define ID_HELPTABLE            1

#define IDD_PRODUCTINFO         1

#define IDS_TITLE               1
#define IDS_TITLE1              2
#define IDS_HELPTITLE           3
#define IDS_ERROR_CREATEHELP    4

#define IDS_ERROR_OPEN_FOR_VERIFY               0x1000
#define IDS_ERROR_FILE_TOO_SMALL                0x1001
#define IDS_ERROR_INVALID_FILE_ID               0x1002
#define IDS_ERROR_INVALID_FILE_VERSION          0x1003
#define IDS_ERROR_INVALID_CONTROL_LABEL         0x1004
#define IDS_ERROR_INVALID_CONTROL_BLOCK_TYPE    0x1005
#define IDS_ERROR_TOO_MANY_ROWS                 0x1006
#define IDS_ERROR_MEMORY1                       0x1007
#define IDS_ERROR_DECODER                       0x1008
#define IDS_ERROR_MEMORY2                       0x1009
#define IDS_ERROR_DC_OPEN                       0x100A
#define IDS_ERROR_PS_CREATE                     0x100B
#define IDS_ERROR_CREATE_BITMAP                 0x100C
#define IDS_ERROR_GET_CODE_SIZE                 0x100D
#define IDS_ERROR_INVALID_CODE_SIZE             0x100E
#define IDS_ERROR_MEMORY3                       0x100F
#define IDS_ERROR_FILE_ERROR                    0x1010
#define IDS_ERROR_OPEN_FOR_LOAD                 0x1011
#define IDS_ERROR_MEMORY4                       0x1012

#endif /* GIF_H */
