/* PTEXT User API functions */

#ifndef PTEXT_H
#define PTEXT_H

#define REVISION     "PText 0.97"
#define REVISION_NO  (97)

#define ID_HELPTABLE               1
                                 
#define IDD_PRODUCTINFO            1

#define IDD_CONFIGURE_IMPORT       2
#define   IDD_CONFIGURE_FONT       200
#define   IDD_CONFIGURE_SIZE       201
#define   IDD_CONFIGURE_METRIC     202
#define   IDD_CONFIGURE_SOFTBREAKS 203

#define IDD_CONFIGURE_EXPORT       3
#define   IDD_CONFIGURE_FORMAT     300
#define   IDD_CONFIGURE_HEIGHT     302
#define   IDD_CONFIGURE_WIDTH      303
#define   IDD_CONFIGURE_BOLD       304
#define   IDD_CONFIGURE_UNDERSCORE 305
#define   IDD_CONFIGURE_STRIKEOUT  306

#define IDS_TITLE                1
#define IDS_TITLE1               2
#define IDS_HELPTITLE            3
#define IDS_ERROR_CREATEHELP     4

#define IDS_MAJORTAB             1000
#define IDS_PTS                  1001
#define IDS_ERROR_INVALIDHEIGHT  1002
#define IDS_ERROR_INVALIDWIDTH   1003
#define IDS_ERROR_OPEN_VERIFY    1004
#define IDS_ERROR_MEMORY_VERIFY  1005
#define IDS_ERROR_HAS_NULLS      1006
#define IDS_ERROR_OPEN_LOAD      1007
#define IDS_ERROR_MEMORY_OPEN    1008
#define IDS_ERROR_WRITE          1009

#endif /* PTEXT_H */
